### ISSUE TITLE
app_url for a bulk board posting

### ISSUE THREAD

**Issue by markzsanantonio** [oneworldmarket/idibu-api#12]
Hi

As an example I am using the [app_url](https://github.com/oneworldmarket/idibu-api/blob/master/api-v3/dyn-vars.md) tag like _my.website.com/application-form/123?source=Glassdoor_ when sending a posting to Glassdoor. This is my way of knowing that the applicant saw the job post from Glassdoor and this works well so far, however, when I do a posting with multiple boards I've noticed that not all of them have an extrafield of _app_url_. For example Google, Trovit does not have any dynamic core field for the _app_url_. Is there a way to make them have their own _app_url_ so that I can use it to redirect applicants to my application form (e.g. _?source=Google_, _?source=Trovit_) on a single posting?

Thanks!

**Comment by idibuseba** [comment]
Hey @markzsanantonio - unfortunately not all websites support Application URL and we have no influence over this.

**Comment by markzsanantonio** [comment]
Hi @idibuseba - I was browsing the docs and I found this [service](https://github.com/oneworldmarket/idibu-api/blob/master/webservices/settings-management/application_url_tracking.md), after reading this is what I need.

Thank you!
