### ISSUE TITLE
Discrepancies between example and docs

### ISSUE THREAD

**Issue by mausch** [oneworldmarket/idibu-api#15]
I'm seeing some differences between the example in https://github.com/oneworldmarket/idibu-api/tree/master/posting-api/examples#standard-test-xml and the documentation in https://github.com/oneworldmarket/idibu-api/blob/master/posting-api/vars.md#core-field-variables-job-tag :

- Example has a tag "sender", docs says "client_reference". They seem to be the same thing but which is the valid one?
- Docs lists "publish" saying it's required but it's not in the example
- Example has "salaryOverride", not present in the docs. 
I see it's mentioned in https://github.com/oneworldmarket/idibu-api/blob/master/posting-api/dyn-vars.md so maybe add a link to this in vars.md ?
- Example has "posts", not present in the docs

**Comment by idibuseba** [comment]
Hey @mausch , thanks for the further feedback!

- `sender` is actually a field that identifies the user of the account. You can find out more about it [here](https://github.com/oneworldmarket/idibu-api/blob/master/posting-api/sender-tags.md).
`client_reference` is used to assign your own unique IDs to jobs but it is best to stick to idibu's `<job id="">` which is returned upon posting and can be further explored via [Job Management Webservice](https://github.com/oneworldmarket/idibu-api/blob/master/webservices/job-management/job-management-webservice.md), especially if you are moving from the previously-used UPP approach.
- Yes, looks like the `publish` parameter isn't required after all, must have been a mistake - I have now fixed it. If not provided, the job will publish ASAP.
- I have now added a link to the Dynamic Variables and Sender Variables in the API Variables article :)
- The `posts` section is covered in further articles - the documentation is constructed in a way that it should be read all one after another. More information can be found [here](https://github.com/oneworldmarket/idibu-api/blob/master/posting-api/spec-data.md). If you plan to continue using PCP, you can probably omit `posts` completely though.

**Comment by mausch** [comment]
Great, thanks 👍
