### ISSUE TITLE
Confusing Boards

### ISSUE THREAD

**Issue by kaitlyntier** [oneworldmarket/idibu-api#9]
I have tried to enter my board IDs like so: `boards=1000%3B1001%3B1002%3B1003`

also tried: `boards=1000;1001;1002;1003`

unfortunately this does not work or have I missed something in the docs?

**Comment by idibuseba** [comment]
Hey @kaitlyntier , what is the exact call that you are trying to perform?

**Comment by kaitlyntier** [comment]
Hi @idibuseba 

I was trying out the UPP, I got a little confused using the boards job's parameter but the rest is okay just the _Published To_ field. I can't seem to populate it with the boards we currently have (e.g. Facebook, Twitter, LinkedIn, etc.), it only display one item _idibu CV Manager_.

![Screen Shot 2019-04-18 at 8 16 23 AM](https://user-images.githubusercontent.com/40883488/56328603-4ae36400-61b2-11e9-8e7d-d3134e5972bf.png)

**Comment by kaitlyntier** [comment]
Hi

It's okay now, the board automatically appears whenever I added a new one. The boards parameter seem to preselected the board's ID.

Thanks!
